services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/myDatabase
    volumes:
      - .:/app  # This maps the current directory to /app in the container
      - /app/venv  # Exclude the venv directory if you have one
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
