name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build Docker containers
        run: docker-compose -f docker-compose.yml build

      - name: Run tests
        run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/
